add oneof support
vizor-games/infraworld-cornerstone pull request #22
Opened 2021-02-18 21:43 UTC by Razangann

add oneof support and fix log4j-api version to actual.

2021-02-19 06:36 UTC, VizorDaeva commented on src/main/java/com/vizor/unreal/convert/ProtoProcessor.java
> +import com.squareup.wire.schema.internal.parser.*;
Уверен что хорошая идея так делать? Так вместо точечных импортов ты тянешь прямо всё (я не знаю на сколько там много этого всего) и это излишние затраты памяти.
Хотя я мыслю с позиции плюсов и может к джаве это и не относится

2021-02-19 06:37 UTC, VizorDaeva commented on src/main/java/com/vizor/unreal/convert/ProtoProcessor.java
> +            //field.addAnnotation(fieldAnnotations);
Забыл удалить?

2021-02-19 08:35 UTC, Razangann commented on src/main/java/com/vizor/unreal/convert/ProtoProcessor.java
> +import com.squareup.wire.schema.internal.parser.*;
Хмм... у меня IDE сам дописывал импорты, я даже не смотрел на них)

2021-02-19 08:38 UTC, Razangann commented on src/main/java/com/vizor/unreal/convert/ProtoProcessor.java
> +            //field.addAnnotation(fieldAnnotations);
Пока не нашел как для  TUnion использовать какой-нибудь UPROPERTY, временно убрал эту строку, думал может кто подскажет и верну аннотацию:)

2021-02-19 08:48 UTC, VizorDaeva commented on src/main/java/com/vizor/unreal/convert/ProtoProcessor.java
> +            //field.addAnnotation(fieldAnnotations);
К сожалению TUnion не может быть UPROPERTY так что просто удаляй её

2021-02-19 14:45 UTC, nikitamiroshnichenko requested changes
oneof realization via TUnion makes oneof fields inaccessible from blueprints. It goes against the original requirements and ideas of Infraworld project

2021-02-19 15:23 UTC, Razangann commented
> oneof realization via TUnion makes oneof fields inaccessible from blueprints. It goes against the original requirements and ideas of Infraworld project

unfortunately TUnion doesn't work with UPTOPERTY. i dont know how to use in blueprints. any suggestions?

2021-02-21 22:06 UTC, nikitamiroshnichenko commented
@Razangann

I think you may try to implement this by creating your own OneOf implementation with TVariant inside

2021-02-22 08:47 UTC, Razangann commented
> @Razangann
> 
> > unfortunately TUnion doesn't work with UPTOPERTY. i dont know how to use in blueprints. any suggestions?
> 
> I think you may try to implement this by creating your own OneOf implementation with TVariant inside in [InfraworldRuntime](https://github.com/vizor-games/InfraworldRuntime) project and adopt Cornerstone then.
TVaritan also cannot handle UPROPERTY.

2021-02-22 08:48 UTC, Razangann commented
> @Razangann
> 
> > unfortunately TUnion doesn't work with UPTOPERTY. i dont know how to use in blueprints. any suggestions?
> 
> I think you may try to implement this by creating your own OneOf implementation with TVariant inside in [InfraworldRuntime](https://github.com/vizor-games/InfraworldRuntime) project and adopt Cornerstone then.

TVaritan also cannot handle UPROPERTY.

2021-02-22 08:49 UTC, Razangann commented
> @Razangann
> 
> > unfortunately TUnion doesn't work with UPTOPERTY. i dont know how to use in blueprints. any suggestions?
> 
> I think you may try to implement this by creating your own OneOf implementation with TVariant inside in [InfraworldRuntime](https://github.com/vizor-games/InfraworldRuntime) project and adopt Cornerstone then.

TVaritan also cannot handle UPROPERTY.

2021-02-22 19:48 UTC, nikitamiroshnichenko commented
> TVaritan also cannot handle UPROPERTY.
Yes, it cant. But as I said above you can implement your own OneOf structure with TVariant inside it.

Something like:
`
USTRUCT()
struct OneOf
{
  GENERATED_BODY()
  // empty stub structrure
};
`

Image that you have oneof fileld in you proto file:
`
message SampleMessage {
  oneof my_oneof {
    string oneofString = 1;
    int32 oneofInteger = 2;
    float oneOfFloat = 3;
  }
}

`

in this case you  need to generate something like this:

`
USTRUCT()
SampleMessage : public OneOf
{
  GENERATED_BODY()
public:
  UFUNCTION(BlueprintCallable)
  FString GetStringValue()
  {
    return Variant.Get<FString>();
  }

  UFUNCTION(BlueprintCallable)
  int32 GetInt32Value()
  {
    return Variant.Get<int32>();
  }

  UFUNCTION(BlueprintCallable)
  float GetFloatValue()
  {
    return Variant.Get<float>();
  }

private:
  TVariant<FString, int32, float> Variant;
};
`

2021-02-22 21:05 UTC, Razangann commented
> > TVaritan also cannot handle UPROPERTY.
> 
> Yes, it cant. But as I said above you can implement your own OneOf structure with TVariant inside it.
> 
> Something like:
> 
> `USTRUCT() struct OneOf { GENERATED_BODY() // empty stub structrure };`
> 
> Image that you have oneof fileld in you proto file:
> 
> ```
> message SampleMessage {
>   oneof my_oneof {
>     string oneofString = 1;
>     int32 oneofInteger = 2;
>     float oneOfFloat = 3;
>   }
> }
> ```
> 
> in this case you need to generate something like this:
> 
> ```
> USTRUCT()
> SampleMessageOneOf : public OneOf
> {
>   GENERATED_BODY()
> public:
>   UFUNCTION(BlueprintCallable)
>   FString GetStringValue()
>   {
>     return Variant.Get<FString>();
>   }
> 
>   UFUNCTION(BlueprintCallable)
>   int32 GetInt32Value()
>   {
>     return Variant.Get<int32>();
>   }
> 
>   UFUNCTION(BlueprintCallable)
>   float GetFloatValue()
>   {
>     return Variant.Get<float>();
>   }
> 
> private:
>   TVariant<FString, int32, float> Variant;
> };
> ```

USTRUCT cannot contain UFUNCTION inside. Also I thought to use USCLASS with UFUNCTION and add to USTRUCT. but the class inside the struct is also not used

2021-03-01 14:49 UTC, merged